vjousse/pomodorolm

- .github/workflows/manual-release.yml
- README.md
- package.json
- src-elm/Main.elm
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src-tauri/tauri.conf.json
- src-ts/main.ts
- vite.config.ts
> fix: manage tick on the rust side

- src-elm/Main.elm
- src-tauri/src/main.rs
- src-ts/main.ts
> fix: minimize to tray on close

- src-elm/Main.elm
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.json
- src-ts/main.ts
> feat: add version number

- src-elm/Main.elm
> fix: play notification at the end of the round

- src-tauri/capabilities/migrated.json
- src-tauri/gen/schemas/capabilities.json
- src-tauri/src/lib.rs
> Add tauri-plugin-shell to open links

- src-tauri/src/lib.rs
> Fix sleep duration for audio play

- src-tauri/src/lib.rs
> Draw background circle for tray icon

- src-tauri/src/lib.rs
> refactor: better error management

- src-elm/Main.elm
- src-tauri/src/lib.rs
- src-ts/main.ts
> fix: change theme only on config load

- .github/workflows/publish-to-auto-release.yml
- bin/release.py
- package.json
- pyproject.toml
- uv.lock
> chore: check versions consistency when releasing

- .github/workflows/snapcraft.yml
> chore: add snapcraft build

- .github/workflows/ci.yml
- bin/release.py
- elm.json
- package-lock.json
- package.json
- review/elm.json
- review/src/ReviewConfig.elm
- src-elm/ListWithCurrent.elm
- src-elm/Main.elm
- src-elm/Themes.elm
- src-ts/main.ts
> chore: add elm-review

- .github/workflows/snapcraft.yml
See https://github.com/canonical/action-build/issues/82
> ci: fix snapcraft build

- src-elm/Main.elm
- src-tauri/src/lib.rs
- src-ts/main.ts
> fix: themes are not always loaded on app start

- .github/workflows/ci.yml
- aur/PKGBUILD
- flatpak/cargo-sources.json
- src-elm/Json.elm
- src-elm/Main.elm
- src-elm/Types.elm
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src-tauri/src/main.rs
- src-tauri/src/pomodoro.rs
- src-tauri/tests/pomodoro_test.rs
- src-ts/main.ts
> refactor: manage state on rust side

- CHANGELOG.md
- aur/PKGBUILD
- org.jousse.vincent.Pomodorolm.metainfo.xml
- package-lock.json
- package.json
- snapcraft.yaml
- src-elm/Main.elm
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.json
> fix: focus notification time

- src-tauri/gen/schemas/macOS-schema.json
- src-tauri/src/lib.rs
> fix: mac osx hide behavior

- src-tauri/src/icon.rs
> fix: bad pause icon rendering

- src-tauri/src/lib.rs
- src-ts/main.ts
> fix: update pomodoro config on config change

- .github/workflows/flatpak.yml
- src-elm/Main.elm
> fix: notification settings

- src-elm/Json.elm
- src-elm/Main.elm
- src-elm/Types.elm
- src-elm/View.elm
- src-tauri/src/lib.rs
- src-ts/main.ts
> feat: add start minimized to tray option

- .github/workflows/ci.yml
- src-elm/ColorHelper.elm
- src-elm/Main.elm
- src-elm/View/Timer.elm
- src-tauri/src/config.rs
- src-tauri/src/gui.rs
- src-ts/main.ts
> fix: app crash if duration is 0
